/**
 * OatMilk.Backend.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ModifierResponse } from './modifierResponse';


export interface EffectResponse { 
    id?: string;
    name?: string | null;
    modifiers?: Array<ModifierResponse> | null;
}

