/**
 * OatMilk.Backend.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ModifierOperation = 0 | 1 | 2 | 3;

export const ModifierOperation = {
    NUMBER_0: 0 as ModifierOperation,
    NUMBER_1: 1 as ModifierOperation,
    NUMBER_2: 2 as ModifierOperation,
    NUMBER_3: 3 as ModifierOperation
};

